- .travis.yml
Integrate travis CI continuous Integration into the primary branch
> Add travis support (initial)

- CMake/portability/BlueGenePortability.cmake
- CMakeLists.txt
- tests/unit/CMakeLists.txt
- tests/unit/tests_high_five_base.cpp
> Enhance IBM BlueGene/Q support

- CMakeLists.txt
Examples are nice but we don't always need to compile them
> Examples compiling optionally

- include/highfive/H5Object.hpp
- include/highfive/bits/H5Object_misc.hpp
> H5Object add missing copy assignment, fixing issue #40

- include/highfive/H5DataSpace.hpp
- include/highfive/bits/H5Converter_misc.hpp
- include/highfive/bits/H5Dataspace_misc.hpp
- include/highfive/bits/H5Utils.hpp
- src/examples/create_attribute_string_integer.cpp
- src/examples/read_write_single_scalar.cpp
- tests/unit/CMakeLists.txt
- tests/unit/tests_high_five_base.cpp
Implement scalar values and scalar string on the model of @ferdonline
but following read/write API and using data_converter mapper
Add new test battery for C++11 support
Add new example for scalar usage
Add new battery of test for every possible scalar type in attribute
> Implement scalar values and scalar string management

- include/highfive/bits/H5Slice_traits.hpp
- include/highfive/bits/H5Slice_traits_misc.hpp
- include/highfive/bits/H5Utils.hpp
as valid datatype for read/write operations
> minor improvement to support container of "const" elements

- CMakeLists.txt
- src/examples/CMakeLists.txt
- tests/unit/CMakeLists.txt
- Avoid issues when using HighFive embedded as a subproject
> Apply patch from Mohamed Ghaith Kaabi <mohamed.kaabi@epfl.ch>

- CMake/PackageConfig.cmake
- CMakeLists.txt
- include/highfive/H5File.hpp
- include/highfive/H5Object.hpp
- include/highfive/bits/H5FileDriver_misc.hpp
- include/highfive/bits/H5Object_misc.hpp
Fixed a bug in Object destructor (call virtual function from destructor).
CMake cleanups.
> Removed unnecessary virtual modifiers.

- README.md
- include/highfive/H5DataSet.hpp
- include/highfive/bits/H5DataSet_misc.hpp
- tests/unit/tests_high_five_base.cpp
As promised. Was much easier than anticipated. 
I'm not sure wether the tests work as expected.
> add getOffset method to DataSet

- include/highfive/H5DataSet.hpp
- include/highfive/H5DataSpace.hpp
- include/highfive/bits/H5DataSet_misc.hpp
- include/highfive/bits/H5Dataspace_misc.hpp
- src/examples/create_extensible_dataset.cpp
- tests/unit/tests_high_five_base.cpp
I took the liberty of cherry picking the code from @jrs65 branch. It should solve Issues #109 and #76.
> Dataset resizing support

- tests/unit/tests_high_five_base.cpp
Quick test addition from #129 .
> Adding test for missmatched diminsions for std::array

- include/highfive/H5DataSpace.hpp
- include/highfive/H5File.hpp
- include/highfive/H5Object.hpp
- include/highfive/bits/H5Attribute_misc.hpp
- include/highfive/bits/H5Converter_misc.hpp
- include/highfive/bits/H5FileDriver_misc.hpp
- include/highfive/bits/H5Node_traits.hpp
- include/highfive/bits/H5PropertyList_misc.hpp
- include/highfive/bits/H5Slice_traits_misc.hpp
- include/highfive/bits/H5Utils.hpp
Fixes various spelling mistakes in comments.
> Spelling correction comments

- include/highfive/bits/H5Node_traits_misc.hpp
> exist: always return true for /

- include/highfive/bits/H5Exception_misc.hpp
> Do not free const char*

- include/highfive/bits/H5Annotate_traits.hpp
- include/highfive/bits/H5Annotate_traits_misc.hpp
- tests/unit/tests_high_five_base.cpp
> AnnotateTraits: add deleteAttribute function

- include/highfive/H5DataSpace.hpp
- include/highfive/bits/H5Dataspace_misc.hpp
- include/highfive/bits/H5Utils.hpp
- tests/unit/tests_high_five_base.cpp
Extracted from the Initial work towards fixed-len strings
> Fix shortcut syntax with plain C arrays

- doc/Doxyfile
- include/highfive/H5DataType.hpp
- include/highfive/bits/H5DataType_misc.hpp
- include/highfive/bits/H5Slice_traits.hpp
- src/examples/create_datatype.cpp
- tests/unit/tests_high_five_base.cpp
> Add support for enums

- src/examples/boost_multiarray_complex.cpp
Fixes #166 
kudos to @HQS-Peter
> Adding example of boost multi_array<std::complex>

- CMake/HighFiveConfig.cmake.in
- tests/test_library/CMakeLists.txt
> Copy less attributes for dependent code.

- include/highfive/H5Easy.hpp
- include/highfive/h5easy_bits/H5Easy_scalar.hpp
> [H5Easy] Updating error message dump

- CHANGELOG.md
Changing date format to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
Thanks @matz-e
> Changing date format

- README.md
Just stumbled upon this little typo
> Fixed typo '-DD' to '-D' in 'Dependencies'.

- .github/workflows/gh-pages.yml
> Fixing minor error in GH Action

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
As proposed in #410 this introduces issue templates for bug reports and feature requests.
closes #410
> Create issue templates

- include/highfive/bits/H5Converter_misc.hpp
I extracted this fix from the PR #400 of @kerim371
> Fix use before initialization

- include/highfive/H5PropertyList.hpp
> Add all property lists alias for completeness

- .github/workflows/ci.yml
See https://github.com/actions/virtual-environments/pull/3056
> Old compilers have been remove from docker image

- CHANGELOG.md
- CMakeLists.txt
It has been a while since there was a release!
> Release 2.3

- include/highfive/bits/H5DataType_misc.hpp
- tests/unit/tests_high_five_base.cpp
See #461 for an extensive description of the problem. Note that given my limited experience with HDF5 and H5 the solution might not be optimal or even sufficient. Your expertise is required to verify that.
Fixes #461
A unit test was created
- OS: Windows
> Resolve an issue where padding of nested compound types were being calculated incorrectly (#461)

- include/highfive/bits/H5Attribute_misc.hpp
- include/highfive/bits/H5ReadWrite_misc.hpp
- include/highfive/bits/H5Slice_traits.hpp
- include/highfive/bits/H5Slice_traits_misc.hpp
Fixes https://github.com/BlueBrain/HighFive/issues/455
It would be good to test on this, but frankly I don't know how to.
> Adding path to type warning message

- README.md
> Add a link to documentation in README

- .github/workflows/ci.yml
- include/highfive/bits/H5DataType_misc.hpp
- tests/unit/tests_high_five_base.cpp
> Add support for long double type

- doc/doxygen-awesome-css/update_doxygen_awesome.sh
The license was missing. This should add the correct one.
> Add license to doxygen-awesome update script

- include/highfive/H5Group.hpp
- include/highfive/bits/H5File_misc.hpp
> add inline specifiers where needed

- include/highfive/H5DataSpace.hpp
- include/highfive/bits/H5DataSet_misc.hpp
- include/highfive/bits/H5Utils.hpp
Was useful before but now code has been move in a single place
> Remove old include of boost/eigen

- .gitmodules
It was never use in this project
> Remove hpc-coding-convention git module

- include/highfive/bits/H5Slice_traits.hpp
- include/highfive/bits/H5Slice_traits_misc.hpp
- tests/unit/tests_high_five_base.cpp
This implements an API for HDF5 hyperslabs. It also reimplements existing selection functionality using the new wrappers.
> Implement an interface for HDF5 hyperslabs.

- include/highfive/bits/H5Slice_traits.hpp
- include/highfive/bits/H5Slice_traits_misc.hpp
Incorporates various improvements made in the review of #538.
> Fixup hyperslab PR #538

- src/examples/read_write_raw_ptr.cpp
This PR adds a simple example for reading/writing arrays with only a raw pointer and a shape. This can hopefully used for cases like #557.
> Add an example for a raw ptr with a shape.

- include/highfive/bits/H5Attribute_misc.hpp
- include/highfive/bits/H5File_misc.hpp
- include/highfive/bits/H5Node_traits_misc.hpp
- include/highfive/bits/H5Path_traits_misc.hpp
- include/highfive/bits/H5Reference_misc.hpp
- include/highfive/bits/H5Utils.hpp
> All get_name functions take size_t and not hsize_t

- doc/poster/index.html
> poster: minor suggestions

- doc/poster/example_easy_h5py.py
- doc/poster/example_easy_highfive.cpp
- doc/poster/examples.js
- doc/poster/index.html
> poster: adding H5Easy example

- include/highfive/bits/H5Slice_traits.hpp
- include/highfive/bits/H5Slice_traits_misc.hpp
> Add block argument to select()

- .github/ISSUE_TEMPLATE/config.yml
- README.md
Make discussions forum more visible to avoid issues being created that are actually questions on how to do things.
> Add issue configuration

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
It will help us to have a comparison
> Add coverage when merge on master

- .github/workflows/ci.yml
A new version have been release follow the stream
> Update hdf5 to 1_13_3 in CI

- .github/workflows/ci.yml
- CMake/HighFiveTargetDeps.cmake
- CMakeLists.txt
- tests/unit/tests_high_five_base.cpp
Add CI which runs HighFive with GLIBCXX_ASSERTIONS, ASAN and UBSAN.
> Improve memory checks

- tests/unit/tests_high_five_base.cpp
The `GROUP_NAME` is likely real on Window. The rest is precautionary.
> A few more potential clashes with macros.

- src/examples/create_attribute_string_integer.cpp
Also show how to write attributes to groups and the file.
> Improve Attribute example.

- include/highfive/bits/H5Node_traits.hpp
- include/highfive/bits/H5Node_traits_misc.hpp
- tests/unit/tests_high_five_base.cpp
- added a method in NodeTraits to create hard links
```bash
cmake ..
make -j8
make test
```
- OS: Ubuntu 22.04.2 LTS (WSL)
- Compiler: gcc 11.3.0
- Dependency versions: hdf5 1.10.7
> added ability to create hard links

- include/highfive/bits/H5Node_traits.hpp
- include/highfive/bits/H5Node_traits_misc.hpp
- tests/unit/tests_high_five_base.cpp
>  Implement creating hard links

- CHANGELOG.md
- README.md
- doc/Doxyfile
- doc/DoxygenLayout.xml
- doc/developer_guide.md
- include/highfive/H5PropertyList.hpp
This commit includes:
* Improved PropertyList documentation.
* A developer guide.
* some minor improvements.
> Improvements to the documentation.

- CMake/config/CompilerFlagsHelpers.cmake
> Fix check of Intel OneAPI compiler

- include/highfive/bits/H5ReadWrite_misc.hpp
This commit extracts the workaround for an ASCII/UTF8 conversion bug, into it's own function. This is a small refactoring without functional changes.
> Localize workaround for an ASCII/UFT8 bug.

- tests/test_project_integration.sh
> Modernize `test_project_integration.sh`.

- README.md
This commit marks the beginning of breaking changes on `master`.
> Start merging `v3` features.

- include/highfive/H5DataType.hpp
> Improve doc of 'HIGHFIVE_REGISTER_TYPE'.

- include/highfive/eigen.hpp
- src/examples/CMakeLists.txt
- src/examples/eigen_map.cpp
- src/examples/eigen_matrix.cpp
- src/examples/eigen_vector.cpp
- tests/unit/data_generator.hpp
- tests/unit/supported_types.hpp
- tests/unit/test_all_types.cpp
- tests/unit/tests_high_five_base.cpp
This commit adds support for Eigen matrices, arrays and maps. Both row- and column-major, but without striding or padding.
> Re-implement Eigen support.

- CMakeLists.txt
- cmake/HighFiveWarnings.cmake
- doc/developer_guide.md
- src/examples/CMakeLists.txt
Includes changes:
* an inconsistency in `HIGHFIVE_MAX_ERRORS`,
* less deeply nest `if-if` statements,
* removes debug output.
> Fix CMake code.

- .github/run_examples.sh
- .github/workflows/ci.yml
- src/examples/parallel_hdf5_collective_io.cpp
> Run parallel examples during CI.
