BlueBrain/HighFive

include/highfive/bits/H5Object_misc.hpp
Triggers a warning in new compilers and it's not recommended because
it can cause double exceptions during stack unwinding.
In C++11 destructors are implicitly noexcept, so std::terminate will be
called unless noexcept(false) (C++11 only syntax) is added.
=> Do not throw from ~Object

CHANGELOG.md, CMakeLists.txt, include/highfive/bits/H5Slice_traits.hpp, include/highfive/bits/H5Slice_traits_misc.hpp
The new one is for plain C arrays. This also solves the annoyance
of having to provide an l-value for T* buffers.
=> Split H5Slice_traits::read in two functions.

include/highfive/bits/H5DataType_misc.hpp
Adds numpy/h5py compatible support for complex as AtomicType.
=> [H5DataType] added h5py compatible support for std::complex<double> data type

include/highfive/bits/H5File_misc.hpp
Currently, Truncate mode can't be used alone. This patch accepts Truncate for H5Fcreate.
=> fix: Truncate mode can create

include/highfive/H5File.hpp, include/highfive/bits/H5File_misc.hpp, tests/unit/tests_high_five_base.cpp
Open modes/flags improved, behavior more according to posix
Added lots of tests
c++linter applied
Respects Hdf5lib better, so that only respective flags are passed to open() or create(), excluding H5F_ACC_CREAT)
=> More resilient open modes

include/highfive/bits/H5File_misc.hpp, tests/unit/tests_high_five_base.cpp
Some additional flag combinations can be incompatible. E.g. File::Truncate | File::Excl, which is detected by hdf5lib.
Even though ReadOnly might seem incompatible with Truncate and Excl, hdf5 says it just ignores it, and actually ReadOnly is the empty flag (0x0), so it won't ever bother.
=> Some more tests to open modes

include/highfive/H5PropertyList.hpp, include/highfive/bits/H5PropertyList_misc.hpp, tests/unit/tests_high_five_base.cpp
This adds support for the deflate (compression) and shuffle (aids compression) filters, using the same interface as for chunking. I include a simple unit-test that writes compressed datasets to files, reads them back and compares. Manual inspection with h5dump shows that the filters are being applied, e.g.:
```
$ h5dump -H -p h5_rw_deflate_x_test.h5 
HDF5 "h5_rw_deflate_x_test.h5" {
GROUP "/" {
DATASET "dset" {
DATATYPE  H5T_STD_I64LE
DATASPACE  SIMPLE { ( 128, 32 ) / ( 128, 32 ) }
STORAGE_LAYOUT {
CHUNKED ( 16, 16 )
SIZE 2623 (12.493:1 COMPRESSION)
}
FILTERS {
PREPROCESSING SHUFFLE
COMPRESSION DEFLATE { LEVEL 9 }
}
FILLVALUE {
FILL_TIME H5D_FILL_TIME_IFSET
VALUE  H5D_FILL_VALUE_DEFAULT
}
ALLOCATION_TIME {
H5D_ALLOC_TIME_INCR
}
}
}
}
```
=> Deflate and shuffle properties

include/highfive/H5DataSpace.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5Dataspace_misc.hpp, include/highfive/bits/H5Slice_traits.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, include/highfive/bits/H5Utils.hpp, tests/unit/tests_high_five_base.cpp
This should add support for std::array, which is missing (though inferior old C style arrays were supported!).
I tried to add a test, as well.
Edit: Addresses #100.
=> Adding support for std::array

tests/unit/CMakeLists.txt, tests/unit/tests_high_five_base.cpp
Quick PR to drop the irritating C++11 checks in the tests that no longer do anything.
=> Dropping old toggle for C++11

include/highfive/H5DataSpace.hpp, include/highfive/H5PropertyList.hpp, include/highfive/bits/H5Dataspace_misc.hpp, tests/unit/tests_high_five_base.cpp
This expands the current shortcut:
DataSpace(3) -> 1D dataspace: [3]
to work with any number of dimensions:
DataSpace(2,3,4) -> 3D dataspace: [2,3,4]
It also fixes the current odd behavior where two integer parameters, DataSpace(1,2) matches against the iterator constructor, which then matches against a different constructor in vector, causing a really odd result. This was done by not allowing an integer-like value through the template for the iterator constructor.
A similar fix was added to Chunking for consistency.
=> Adding variadic DataSpace and Chunking constructor

include/highfive/bits/H5Converter_misc.hpp, tests/unit/tests_high_five_base.cpp
This is the test mentioned in #135, and a possible fix. Only fixes 1D vectors and arrays at the moment.
It works by giving the unnested vector and array converters a filtered version of the dimensions array, where all the 1s have been removed unless it is all 1s, in which case a single 1 is kept.
Higher dimensional arrays may still have issues where they don’t throw an error, but miss the correct non-1 dimensions.
=> Fix broadcasting on read

include/highfive/H5Exception.hpp
One line fix: clears the (not enabled) `-Wsuggest-override` warnings.
=> explicitly override std::exception::what()

include/highfive/H5DataSpace.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, src/examples/boost_ublas_double.cpp
On some versions of Boost (1.64, at least), you can't import ublas without a specific header first. See [this issue](https://stackoverflow.com/questions/44534516/error-make-array-is-not-a-member-of-boostserialization). This fixes it by importing the extra required header first in HighFive.
Could it be possible to just add definitions instead of importing the boost headers? And then the imports would only be needed in user code if the user actually used the boost features. Not sure if it would work, but it would be much nicer if it did.
PS: Though the issue I linked didn't mention it, for me it seems to not be necessary on Boost 1.68; I only noticed this when running with 1.64.
=> Fix missing include for old versions of BOOST

include/highfive/H5File.hpp
This solves #150, the missing definition of the member variables.
=> Replace static const members with unnamed enums

CMake/PackageConfig.cmake, CMakeLists.txt, README.md
This PR adds support for cmake package version.
The befit is that downstream projects can request a specific version, like
```
find_package(HighFive 2.0.0 REQUIRED)
```
=> CMake/PackageConfig.cmake: added support for package version

include/highfive/bits/H5Easy_misc.hpp
The file `H5Easy_misc.hpp` is using the alternate form of the not operator, `not` instead of `!`. While this is valid C++, it is not valid C, and requires MSVC to be put into a standards-conforming mode (`/permissive-`) that is not compatible with some Windows headers. (See [here](https://stackoverflow.com/questions/24414124/why-does-vs-not-define-the-alternative-tokens-for-logical-operators) and [there](https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019))
To keep to compatibility high, I would therefore suggest to use the traditional form of `not` instead.
=> H5Easy: fix compatibility with MSVC

include/highfive/H5Attribute.hpp, include/highfive/H5DataSet.hpp, include/highfive/H5Object.hpp, include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5DataSet_misc.hpp, include/highfive/bits/H5Dataspace_misc.hpp, include/highfive/bits/H5Exception_misc.hpp, include/highfive/bits/H5Node_traits_misc.hpp, include/highfive/bits/H5PropertyList_misc.hpp, include/highfive/bits/H5Utils.hpp
This fixes all remaining MSVC type conversion warnings (both x64 and x32
build) and one "code unreachable" warning (by marking
HDF5ErrMapper::ToException as [[noreturn]]).
Also, in DataSpace::getMaxDimensions it fixes the H5S_UNLIMITED ->
DataSpace::UNLIMITED replacement to work on the correct vector.
Fixes #164
=> Fix MSVC warnings

include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5Dataspace_misc.hpp
After PR #169 there is still a warning remaining when building for win32
where sizeof(size_t) > sizeof(unsigned int). Fix it by using brace
initialization which requires that the value inside is exactly
representable in size_t. This is better than the static_cast used in the
initial version of PR #169.
=> Fix another MSVC warnings when building for win32

.travis.yml
Travis OSX builds are failing for some reason due to an error from homebrew.
See the following links for people discussing this at the travis community page:
* here: https://travis-ci.community/t/xcode-8-3-homebrew-outdated-error/3798
* https://travis-ci.community/t/issue-brew-formula-installation-fails-due-to-being-outdated/3872
* https://travis-ci.community/t/previously-working-build-failing-with-services-are-not-supported-on-osx/3960/2
* https://travis-ci.community/t/osx-homebrew-addons-module-not-as-reliable-as-claimed/4054
=>  workaround for Travis OSX build failures 

CMake/portability/CheckCXXStandardSupport.cmake
Since some c++11 features are supported since old MSVC versions,
even before -std flags, we let the compiler attempt to compile.
For C++14 and 17 we depend on the -std flags which is ok since 2015u3
understands them and 2015 is the first with c++14 support
Source: https://en.cppreference.com/w/cpp/compiler_support
Fixes #190
=> Dropping invalid MSVC C++11 flag. Assume support

include/highfive/bits/H5Converter_misc.hpp
Change signature of the functions to force a different name mangling which allows MSVC to compile the code. The issue, according to what I've been able to find, is that MSVC cannot disambiguate between a const vs non const function parameter when doing name mangling. Clang and GCC use a different mangling and are able to tell the difference and as such can disambiguate between the candidates. GCC and Clang have conforming behavior and MSVC does not.
Fixes #171 and #104
I reported the issue to Microsoft here https://developercommunity.visualstudio.com/content/problem/736092/standards-conforming-code-returns-c2668-ambiguous.html
It is highly unlikely that MS will be able to fix this issue as it is core to how their name mangling works and likely would cause ABI issues to make changes.
=> Fix MSVC issue with 2D Vectors

.travis.yml
The QuantStack channel on conda was merged into the conda-forge channel. The QuantStack channel was removed: trying to use it results in an error: https://travis-ci.org/BlueBrain/HighFive
=> Fixing CI - switched to correct Conda channel

.travis.yml, CMake/PackageConfig.cmake, CMakeLists.txt
=> Fix build of parallel

CMake/config/CompilerFlagsHelpers.cmake
Conversion warnings are too common to be treated as errors (since we use -Werror). Such warnings are even found within boost libraries, so there is no way around.
This patch simply turns them non-errors again. The warnings are still raised.
Also, avoiding passing unknown options to ICC.
Fixes #243
=> Avoid conversion warnings being treated as errors

tests/unit/tests_high_five.hpp, tests/unit/tests_high_five_parallel.cpp
Without the semicolon building HighFive fails with:
```
HighFive/tests/unit/tests_high_five_parallel.cpp:40:1: error: expected initializer before ‘template’
40 | template <typename T>
```
Tested with `gcc 9.2.1` and `boost 1.67.0.2`.
=> Missing semicolon

include/highfive/H5Exception.hpp, include/highfive/bits/H5Utils.hpp
It is written "kept for compatibility" but it's use only in a private part and declare in "details" namespace.
=> Remove old "using namespace"

include/highfive/H5Easy.hpp, include/highfive/h5easy_bits/H5Easy_Eigen.hpp, tests/unit/tests_high_five_easy.cpp
Fixes #286 
It needed to be verified if the CRTP is satisfied. In any case the implementation offers a significant simplification in the internal implementation.
=> Adding Eigen::Ref to H5Easy (and simplifying Eigen overload)

CMakeLists.txt, include/highfive/H5DataSpace.hpp, include/highfive/H5DataType.hpp, include/highfive/H5Selection.hpp, include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5ConverterEigen_misc.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5DataSet_misc.hpp, include/highfive/bits/H5DataType_misc.hpp, include/highfive/bits/H5Dataspace_misc.hpp, include/highfive/bits/H5Iterables_misc.hpp, include/highfive/bits/H5Node_traits.hpp, include/highfive/bits/H5Node_traits_misc.hpp, include/highfive/bits/H5ReadWrite_misc.hpp, include/highfive/bits/H5Selection_misc.hpp, include/highfive/bits/H5Slice_traits.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, include/highfive/bits/H5Utils.hpp, include/highfive/h5easy_bits/H5Easy_Eigen.hpp, include/highfive/h5easy_bits/H5Easy_xtensor.hpp, src/examples/CMakeLists.txt, src/examples/create_attribute_string_integer.cpp, src/examples/read_write_fixedlen_string.cpp, tests/unit/tests_high_five.hpp, tests/unit/tests_high_five_base.cpp
* Adds core support and API for fixed length strings
* Change `write(const T*)` to `write_raw(const T*, const DataType& dtype = DataType())`.
The change of the name is intended to fix #275, while the introduction of the optional dtype allows users to raw write data structures whose type is ambiguous (e.g. char[] is fixed-string or int8 array?)
The type `char[N]` is now considered a valid Atomic type. The user can therefore
```c++
// create  a dataset for fixed length strings as 
ds = file.createDataSet<char[10]>("ds1", dataspace);
// write raw data
char my_strings[][10] = {"abc", "def"};
ds.write(my_strings);
```
While the previous API is great for performance, a high level API was also introduced, compatible with the short-circuit syntax:
```c++
// Have FixedLenStringArray initialised …
```
=> Support for Fixed-length strings

include/highfive/H5Utility.hpp, include/highfive/bits/H5Node_traits.hpp, include/highfive/bits/H5Node_traits_misc.hpp
The implementation of `Node.exist()` required catching an exception that we generated ourselves. Despite being a simple principle, it kind of used exceptions for flow control and In some compiler toolchains (QT) this would create unwanted error messages (#224, #289)
Makes the low-level `_exist` function conditionally treat the error as a normal false, not throwing exception. This design even simplified the implementation of the public `exist()` method.
Fixes #289
=> Dont rely on exception in node.exist

.gitignore, include/highfive/H5Attribute.hpp, include/highfive/H5DataSet.hpp, include/highfive/H5DataSpace.hpp, include/highfive/H5DataType.hpp, include/highfive/H5Exception.hpp, include/highfive/H5File.hpp, include/highfive/H5Group.hpp, include/highfive/H5Object.hpp, include/highfive/H5Reference.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5DataType_misc.hpp, include/highfive/bits/H5Reference_misc.hpp, tests/unit/tests_high_five_base.cpp
Adds support for HDF5 [references](https://confluence.hdfgroup.org/display/HDF5/References). To keep things simple we support for now only object references (no region references, which are also not supported in parallel HDF5).
We introduce a new `Reference` class that represents an HDF5 object reference when writing to or reading from a file.
Unlike soft and hard links references can be stored and read as data in HDF5 files as Datasets. They can be used to create more complex data relationships beyond vectors and matrices.
Here is a minimal example to create and read an HDF5 reference with the new `Reference` class:
```c++
// write references
{
File file("example.h5", File::ReadWrite | File::Create | File::Truncate);
// Create some data and write it into a DataSet
auto data = …
```
=> HDF5 object references

include/highfive/bits/H5Reference_misc.hpp
Helps to prevent redefinition errors when building downstream projects.
=> Add inline to Reference::get_ref

include/highfive/bits/H5Node_traits_misc.hpp
`SilenceHDF5` should be enabled when `raise_error` is set to `false`. This should fix #331 and #326.
=> Fix SilenceHDF5 initialization for NodeTraits

include/highfive/H5Easy.hpp, include/highfive/h5easy_bits/H5Easy_Eigen.hpp, include/highfive/h5easy_bits/H5Easy_misc.hpp, include/highfive/h5easy_bits/H5Easy_scalar.hpp, include/highfive/h5easy_bits/H5Easy_vector.hpp, include/highfive/h5easy_bits/H5Easy_xtensor.hpp, src/examples/easy_load_dump.cpp, tests/unit/tests_high_five_easy.cpp
This is something like proof of concept (it does not compile) for SFINAE so that load/dump can be easily tailored for specific types incl. CPRT (Eigen).
Generic functions (for scalars, strings) are limited via the `is_easy`, specially treated is vector with `is_vector`. This is good for dumping.
For loading, I am too dumb to make load_impl available with enable_if only as needed, maybe someone could figure that out better than me.
=> SFINAE for eigen

CMake/HighFiveConfig.cmake.in
I was inspired by Qt5CoreConfig.cmake.
We have to do that if the project is included several time, for example by Brion.
`Brion` include `HighFive` and `MVDTool`.
`MVDTool` include `HighFive`
This cause a failure because the target `HighFive` is defined twice.
=> Add a mechanism to not include target HighFive several times

include/highfive/H5Attribute.hpp, include/highfive/H5Easy.hpp, include/highfive/bits/H5Attribute_misc.hpp, include/highfive/h5easy_bits/H5Easy_Eigen.hpp, include/highfive/h5easy_bits/H5Easy_misc.hpp, include/highfive/h5easy_bits/H5Easy_public.hpp, include/highfive/h5easy_bits/H5Easy_scalar.hpp, include/highfive/h5easy_bits/H5Easy_vector.hpp, include/highfive/h5easy_bits/H5Easy_xtensor.hpp, src/examples/easy_attribute.cpp, src/examples/easy_dumpoptions.cpp, tests/unit/tests_high_five_easy.cpp
Allows a variable number of dump-settings (in arbitrary order): The original `H5Easy::DumpMode`, the new `H5Easy::Compression`, and other further other options.
Can you give feedback? @spacescientist @eudoxos 
Fixes https://github.com/BlueBrain/HighFive/issues/301
Fixes #340
=> Adding missing function to H5Attribute; [H5Easy] Enabling compression & Adding attributes

include/highfive/bits/H5Reference_misc.hpp
Because there is a cast:
- Before version 9, GCC warns if not used.
- After version 9, GCC warns if used.
=> Use std::move in NRVO depending of version of GCC

include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5ConverterEigen_misc.hpp, include/highfive/bits/H5DataType_misc.hpp, include/highfive/bits/H5Dataspace_misc.hpp, include/highfive/bits/H5ReadWrite_misc.hpp, include/highfive/bits/H5Utils.hpp
Fix vector<Eigen::Matrix> and boost::multi_array<Eigen::Matrix>, from now
Eigen::Matrix has 2 dimensions and no more 1 with hackish things.
=> Move array_dims in the future manipulator

CMake/HighFiveTargetDeps.cmake
Fixes https://github.com/BlueBrain/HighFive/issues/387
=> Adding CMake include guard

CMakeLists.txt
* **problem**
I use HighFive in another project with documentation that I build with "make doc".  But cmake complains a target "doc" already exists in HighFive.
* **solution** 
With this PR one can disable HighFive documentation building with `set(HIGHFIVE_DOC OFF)` just before `add_subdirectory(/path/to/HighFive)`.
=> optional documentation building in cmake

.github/workflows/gh-pages.yml, .github/workflows/pages.yml, README.md, doc/environment.yaml
Since recently I have been using GitHub Actions to build my docs and upload them to GitHub pages. I set this now to be done when something is pushed to the master, but it could also be done upon releasing.
=> Uploading docs to gh-pages using GitHub Actions

include/highfive/bits/H5Node_traits_misc.hpp
To make existence checks less noisy, we have the HDF5 always initialized with true, regardless of whether an exception is to be raised or not.
This fixes #376
=> Initialize SilenceHDF5 to true in _exist

.github/build.sh, .github/workflows/ci.yml
This PR introduces  GitHub actions-based CI
The strategy is to test for several Linux (Ubuntu) systems, for several compilers, Mac and Windows
Total: 10 jobs
**Combinations**
```
Linux_MPI:
os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
compiler: (default/old)
options: PARALLEL_HDF5 + XTENSOR + EIGEN
Linux_Compilers:
runs-on: ubuntu-18.04
compilers: [clang-8, clang-9, gcc-8, gcc-9,  gcc-10]
options: EIGEN
MacOS: (default compiler + EIGEN)
Windows: (Default compiler + EIGEN + Xtensor)
```
Fixes #402
=> Introducing GitHub Actions CI

.travis.yml, include/highfive/H5Attribute.hpp, include/highfive/H5DataSet.hpp, include/highfive/H5File.hpp, include/highfive/H5Group.hpp, include/highfive/H5Object.hpp, include/highfive/bits/H5Annotate_traits_misc.hpp, include/highfive/bits/H5DataSet_misc.hpp, include/highfive/bits/H5Node_traits.hpp, include/highfive/bits/H5Node_traits_misc.hpp, include/highfive/bits/H5Path_traits.hpp, include/highfive/bits/H5Path_traits_misc.hpp, tests/unit/tests_high_five_base.cpp
**Problem**
1. `getFile()` would be useful to get back the file object from any Group/Dataset/Attribute.
2. `getPath` was duplicated in some entities.
3. With MPI-IO, closing a file invalidates open objects.
**This PR**
Addresses all three problems by creating a PathTraits class and applying it to Group, Dataset and Attribute.
Trait keeps a file obj ref so that it's count never drops to 0.
*Extra Required fixes*:
- Impl `operator==` in object
- Annotate Traits to not construct an empty `Attribute`, but use `Object(hid)` ctr instead
- Drop Clang tests in Travis since we'r covering all of them in the new GitHub Actions CI. Kept only the very old systems tests
=> Generalizing getPath and adding getFile as PathTraits

include/highfive/H5File.hpp, include/highfive/bits/H5File_misc.hpp
This enables recreating file objects and still being able to
call getName()
_filename becomes a cache variable, so we dont change API nor ABI
**Fixes**
Issue when recreating file object from any dataset/group ->getFile()
ctest (already covered, just reimplemented)
=> Implementing getting the filename dynamically

include/highfive/H5PropertyList.hpp, include/highfive/bits/H5Node_traits_misc.hpp, include/highfive/bits/H5PropertyList_misc.hpp
Add a new property in the high level class of properties.
As documented in https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-SetCreateIntermediateGroup
This property let you decide if missing parent's groups should be created when creating a group or a dataset.
As it is already use internally, I though it was a good idea to add it.
This is to complete a bit : #419
=> Add property CreateIntermediateGroup

include/highfive/bits/H5Node_traits.hpp, include/highfive/bits/H5Node_traits_misc.hpp, include/highfive/h5easy_bits/H5Easy_misc.hpp, include/highfive/h5easy_bits/H5Easy_scalar.hpp
This way the parents group can be created automatically if they don't exist.
Deprecate the function *createGroupsToDataSet* inside the easy part and stop using it internally
=> Add option *parents* to createDataSet

src/examples/read_write_vector_dataset_references.cpp
I included an example to demonstrate how references work in HighFive. PR suggested by @tdegeus 
Thank you guys
=> An example using hdf5 references (#396)

include/highfive/H5File.hpp, include/highfive/H5FileDriver.hpp, include/highfive/H5PropertyList.hpp, include/highfive/bits/H5Node_traits.hpp, include/highfive/bits/H5PropertyList_misc.hpp, tests/unit/tests_high_five_base.cpp
This PR implements improvements on property lists, as a follow up to #427, namely:
-  Property lists inherit from object so they can be copied and moved and their ref-count properly managed.
-  Introduce a shared DefaultPropList singleton to avoid always creating the default objects
-  Some code cleanup
Added to `tests_high_five_base`. Run with `ctest`
=> Cleaning up and improving property lists

include/highfive/H5DataSet.hpp, include/highfive/H5Group.hpp, include/highfive/bits/H5Path_traits_misc.hpp, tests/unit/tests_high_five_base.cpp
Default constructors are not recommended since it opens more
room for errors, and thus they had been removed in PR 417
However, before completely remove them, let them be well marked
deprecated with a nice compilation notice
tests added to `tests_high_five_base`. Use ctest
=> Bring back default ctors with Deprecation notice

include/highfive/bits/H5ReadWrite_misc.hpp
When reading ASCII-based datasets without first accessing other datasets, HDF5 produces unexpected converter issues. The patch provides the following fixes:
The issue was reported here https://github.com/BlueBrain/libsonata/issues/139.
Through `libsonata`, it can be easily tested with Python:
```python
import libsonata
filename = "/gpfs/bbp.cscs.ch/project/proj12/jenkins/cellular/circuit-1k/nodes.h5"
pop = libsonata.NodeStorage(filename).open_population("All")
pop.get_attribute('region', libsonata.Selection((1,2)) )
```
Alternatively, the following C++ source code example can be compiled as well:
```C++
vector<std::string> buffer;
HighFive::File file("/gpfs/bbp.cscs.ch/project/proj12/jenkins/cellular/circuit-1k/nodes.h5"); …
```
=> Fix for unexpected issue in HDF5 with ASCII reading

CMake/HighFiveConfig.cmake.in
Improved CMake config in HighFiveConfig.cmake.in.
Because of new policy, option() may not have any effect.
Therefore we swicthed to set(CACHE) and attempt to respect the
previous non-cached variables
Fixes #415 
Our magnanimous CI
=> Improved using CMAKE options from clients

.github/workflows/integration_trigger.yml
Instead of running integration tests important to BlueBrain only inside this repo, we have moved them into a separate repository. This PR only adds a simple webhook that is triggered whenever a PR is merged to notify the external repo that it should run its CI. This makes BlueBrain integration tests completely independent from development here. The PR is merged regardless. It will be up to BlueBrain devs to fix regressions.
=> Add a trigger on PR merge

.github/workflows/ci.yml, include/highfive/H5PropertyList.hpp, include/highfive/bits/H5PropertyList_misc.hpp, tests/unit/tests_high_five_base.cpp
HDF has default support for SZIP, but commercially licensed.
Using `libaec` SZIP can be used with a permissive license.
This commit allows SZIP to be defined as a property.
The good news is I added a test (which is mostly copy-paste of the shuffle-deflate test). The bad news is I was unable to run the test successfully on my machine (not sure why that is, however compiling succeeds and I've also tested it by using it in my own code). I advise you to run the test yourself. You might want to install https://www.dkrz.de/redmine/projects/aec/wiki/Downloads instead of using the built-in szip for licensing reasons, and there may be some cmake configuration needed.
=> Add SZIP support (#435)

include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5DataType_misc.hpp, tests/unit/tests_high_five_base.cpp
Reading attributes now uses the same routines as reading datasets.
Besides the smaller code due to reuse, now it support fixed-length
strings
Fixes #322 and #285
Tests were added to `tests_high_five_base.cpp` in `HighFiveFixedLenStringArrayAttribute`
=> Unified reading/writing attributes and datasets

.github/workflows/ci.yml
* drop previous runs for subsequent updates 
* make use of new GHA concurrency feature
* concurrency group consists of workflow_name#github_ref
* see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
=> GHA: drop previous runs

src/examples/compound_types.cpp
This example shows all the steps for using compund datatypes. Compound attribute writing is also tested here.
**Testing**
Examples are automatically picked up by our CI.
Also checked locally for validity of output
```
Size2D                   Type
Location:  1:800
Links:     1
Type:      shared-1:800struct {
"width"            +0    native double
"height"           +8    native double
} 16 bytes
dims                     Dataset {2/2}
Location:  1:1280
Links:     1
Storage:   32 logical bytes, 32 allocated bytes, 100.00% utilization
Type:      struct {
"width"            +0    native double
"height"           +8    native double
} 16 bytes
group1                   Group
Attribute: dims {2}
Type:      struct {
"width"            +0    native double
"height"           +8 …
```
=> Adding compound types example

tests/unit/CMakeLists.txt
Fixes #474 
```bash
mkdir build
cmake ..
cmake --build .
```
- OS: Windows
- Compiler: MSVC 16.10.1+2fd48ab73
=> Fix bigobj issue when compiling tests on MSVC (#474)

include/highfive/H5DataSpace.hpp, include/highfive/bits/H5Dataspace_misc.hpp, tests/unit/tests_high_five_base.cpp
Fixes typo in `enum DataspaceType` from datascape to dataspace.
[!] This might break some projects that uses the enum directly.
=> Fixes dataspace typo (datascape)

.github/workflows/ci.yml
This platform has been remove 20th september 2021
See: https://github.com/actions/virtual-environments/issues/3287
=> Remove CI with ubuntu 16.04 as github no more support it

include/highfive/bits/H5Utils.hpp
As described in [this comment](https://github.com/BlueBrain/HighFive/issues/172#issuecomment-988148646), when passing an `std::vector` of zero size, the current code invokes undefined behavior, because `val[0]` accesses a nonexistent element. This may cause some unexpected (but valid) complaints by some compilers.
Fixes #172.
Tested using the following commands.
```bash
cmake ..
make -j8
make test
```
- OS: Ubuntu 20.04.1 LTS (WSL)
- Compiler: GCC 9.3.0
- Dependency versions: hdf5 1.10.4+repack-11ubuntu1
=> Fix UB when passing std::vector with size zero

CMake/HighFiveTargetDeps.cmake, include/highfive/H5File.hpp, include/highfive/H5FileDriver.hpp, include/highfive/H5Group.hpp, include/highfive/H5PropertyList.hpp, include/highfive/bits/H5FileDriver_misc.hpp, include/highfive/bits/H5File_misc.hpp, include/highfive/bits/H5Node_traits.hpp, include/highfive/bits/H5Node_traits_misc.hpp, include/highfive/bits/H5PropertyList_misc.hpp, tests/unit/tests_high_five_base.cpp
Added property list modifiers for file creation:
* `FileVersionBounds`
* `MetadataBlockSize`
also added functions to retrieve these settings from the `File` objects.
Added property list modifiers for groups:
* `EstimatedLinkInfo`
also added a new function for group creation to be able to use this modifier, and to retrieve settings. This requires creating a file that has a lower version bound for HDF5 1.8.
=> Add more file and group property list modifiers 

include/highfive/bits/H5DataType_misc.hpp
The previous usage of H5T_NATIVE_CHAR for `signed char` fails on
Fedora/aarch64.  Needed for BlueBrain/libsonata#184.
=> bugfix: always refer to the proper signed type for `signed char`

include/highfive/H5FileDriver.hpp, include/highfive/H5PropertyList.hpp, include/highfive/bits/H5FileDriver_misc.hpp, tests/unit/tests_high_five_parallel.cpp
Follow-up to #500, moves the property list manipulation relating to
files into H5PropertyList.hpp, while also removing the template for MPI
file opening and moving to preprocessor conditionals.
IMO this is a bit cleaner and feels more natural when using the
modifier.
=> Refactor and move file related property list stuff

include/highfive/H5DataType.hpp
I was getting the error "namespace definition is not allowed here" here when calling HIGHFIVE_REGISTER_TYPE. This fixes that error.
- [x ] Issue 1 fixed
Fixes #(issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce if there is no integration test added with this PR. Please also list any relevant details for your test configuration
```bash
cmake ..
make -j8
make test
```
- OS: [e.g. Ubuntu 20.04]
- Compiler: [e.g. clang 12.0.0]
- Dependency versions: [e.g. hdf5 1.12]
=> Fix "namespace definition is not allowed here"

src/examples/CMakeLists.txt, src/examples/eigen_matrix.cpp
This PR adds one example of writing an `Eigen::MatrixXd` to disk using `File::createDataset` directly.
It also adds to the build-system to exclude Eigen examples if H5 is being built without Eigen.
=> Add an example for Eigen.

tests/unit/tests_high_five_base.cpp
In the unit test `CHECK` is used throughout. Even in loops to check that all the elements in two arrays are equal. When several tests fail, this can generate enough lines to overflow the scroll back buffer, e.g. for VS Code.
When checking that all elements of an array are equal it's suffices to print one failing number and then stop the test.
This PR switches to `REQUIRE` for all assertions happening in a loop. Assertions outside of loops remain `CHECK` since it can be convenient to see several failed assertions for a single test.
=> Use `REQUIRE` in loops.

include/highfive/bits/H5Slice_traits_misc.hpp, tests/unit/tests_high_five_base.cpp
Expanding on the work in #538 this PR enables reading and writing to and from irregular hyperslabs from and to 1D memory. Note that the dataset can have any dimension. Therefore, any selection in filespace is now possible. Currently, no selection in memspace is supported. Therefore the API can cleanly support reading and writing to 1D memory.
Why is only 1D memory supported? The issue lies with non-contiguous memory such a `std::vector<std::vector<double>>` in order to read the selection back into the correct location in memory either substantial indexing logic would need to be re-implemented; or the entire array would first need to be written to the flat temporary buffer passed to HDF5 for reading/writing.
Since the general case is substantially more complex than ad hoc solutions for …
=> Read/Write irregular hyperslab into 1D memspace.

include/highfive/H5DataType.hpp, src/examples/compound_types.cpp, src/examples/create_attribute_string_integer.cpp, src/examples/create_datatype.cpp, src/examples/create_extensible_dataset.cpp, src/examples/renaming_objects.cpp
* block creation of empty Enum (hdf5 segfault with them)
* fix examples to use create_datatype instead of AtomicType (more idiomatic)
=> Improve EnumType API

doc/poster/example1_highfive.cpp, doc/poster/example6.cpp, doc/poster/example_boost_ublas.cpp, doc/poster/example_eigen.cpp, doc/poster/example_props.cpp, include/highfive/H5PropertyList.hpp, src/examples/create_attribute_string_integer.cpp
Minor changes
---
Also, there is this declaration of a C array declaration with a non-static size 
https://github.com/BlueBrain/HighFive/blob/a0ed166c4221558acc51b9bc9e86be29d4cab835/doc/poster/example1_hdf5.cpp#L9-L10
Looks like a C99 extension.
=> Minor fixes to build the poster code

include/highfive/bits/H5Slice_traits.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, tests/unit/tests_high_five_base.cpp
Since the dimensions of the array into which the selection will be read should be clear without knowing if the hyperslab happens to be regular, we can only support reading general hyperslabs into 1D arrays.
We therefore remove unused functions which should restore HDF5 1.8 compatibility.
The lost functionality can be recoverd by providing means of checking if a hyperslab is regular, and returning the regular hyperslab if it is. One would then add a further overload `select(const RegularHyperSlab &)` which reads the regular hyperslab into a packed array, similar to how selecting columns works. However, both of these are not supported in HDF5 1.8.
=> `select(const HyperSlab&)` reads into 1D arrays, only.

doc/poster/example1_hdf5.cpp, doc/poster/example1_highfive.cpp, doc/poster/example6.cpp, doc/poster/example_boost.cpp, doc/poster/example_boost_ublas.cpp, doc/poster/example_eigen.cpp, doc/poster/example_props.cpp, doc/poster/index.html, include/highfive/H5PropertyList.hpp, src/examples/create_attribute_string_integer.cpp
We push here a few more fixes and additions to finalize the website for the poster.
The version that is currently deployed on gh-pages is here: https://go.epfl.ch/hi5
=> Code fixes and website improvements

include/highfive/bits/H5DataType_misc.hpp
Computation of padding takes size_t types that are unsigned.
If member_size is smaller than current_size, the compute is bad.
=> Fix computation of PADDING

include/highfive/bits/H5DataType_misc.hpp, tests/unit/tests_high_five.hpp
This MR introduces support for `std::complex<float>`. 
I added the `std::complex<float>` type to the `numerical_test_types` (as `fcomplex` and renamed `complex` to `dcomplex`) and added a corresponding generator.
- OS: MacOS 12.3.1
- Compiler: clang 13.0.1
- Dependency versions: hdf5 1.12.1
=> Support complex float

include/highfive/bits/H5Object_misc.hpp
=> if _hid is 0 it is invalid but not equal to H5I_INVALID_HID

CHANGELOG.md, CMakeLists.txt
This release restores compatibility with HDF5 1.8 and removes quirky behaviour from `select(const HyperSlab &)`.
=> Prepare `v2.4.1`.

include/highfive/H5Object.hpp
PathTraits added as friend of object
Fixes #577
Build master with cmake Visual Studio 15 2017 generator, arch x64, on windows 10
Change the C++ language standard to c++17 (or later) in the Visual Studio UI (Configuration Properties -> C/C++ -> Language -> C++ Language Standard) in one of the examples or tests, and then try to build.  The code should now build correctly.
- OS: Windows 10
- Compiler: Visual Studio 15 2017
=> Build fix for Visual Studio 2017 with c++17 or later

.github/workflows/ci.yml, doc/poster/example_easy_highfive.cpp, include/highfive/bits/H5DataType_misc.hpp, tests/unit/tests_high_five_base.cpp
It seems that it can fix everything and staying > 0 in the same time.
=> Fix padding of compound types

CMake/HighFiveTargetDeps.cmake, CMakeLists.txt, README.md, include/highfive/bits/H5DataType_misc.hpp, src/examples/CMakeLists.txt, src/examples/create_dataset_half_float.cpp, tests/unit/tests_high_five.hpp
Although 16-bit float is not a native C++ type, it is widely used to save runtime and disk space in situations where high precision is not needed, most notably in deep-learning applications. Python's `h5py` trivially supports the creation of `float16` datasets (`type "<f2"`). This PR adds optional support for half-precision in HighFive.
**Code change summary**
- The main code change is in `include/highfive/bits/H5DataType_misc.hpp`, where the `AtomicType` constructor was specialized for `float16_t`
- The type list `numerical_test_types` was augmented by adding `float16_t` (if enabled)
- Added example code `create_dataset_half_float.cpp` in `src/examples`
- A few makefile changes
Download the (single-header) `Half` library from …
=> Support for half-precision (16-bit) floating-point datasets

.github/workflows/ci.yml, include/highfive/bits/H5DataType_misc.hpp
When compiling `@develop` through Spack it would error with:
```
407    In file included from /gpfs/bbp.cscs.ch/home/groshein/HighFive/include/highfive/H5DataType.hpp:395,
408                     from /gpfs/bbp.cscs.ch/home/groshein/HighFive/spack-build-v3pxph2/tests/unit/tests_H5DataType.cpp:3:
409    /gpfs/bbp.cscs.ch/home/groshein/HighFive/include/highfive/bits/H5DataType_misc.hpp: In constructor 'HighFive::AtomicType<T>::AtomicType()':
>> 410    /gpfs/bbp.cscs.ch/home/groshein/HighFive/include/highfive/bits/H5DataType_misc.hpp:205:28: error: 'inspector' is not a member of 'HighFive::details'
```
which points to a missing include in `bits/H5DataType_misc.hpp`.
This MR adds the missing include and activates the CI that checks for these types of issues in CI.
=> Fix missing include.

include/highfive/H5PropertyList.hpp, include/highfive/bits/H5PropertyList_misc.hpp, include/highfive/bits/H5Slice_traits.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, src/examples/parallel_hdf5_write_dataset.cpp
Make it possible to request collective I/O for H5Dwrite and H5Dread.   Like HDF5 itself, users have to opt-in with an 'enable' call. 
I'm brand new to HighFive, and have developed a lot more C code than C++ code, so I would appreciate a review to make sure I'm doing this the HighFive way
fixes #112 
Also in this pull request are some updates to the parallel write test
- make the memory type match the file type
- request collective I/O
- 
- Dependency versions: collective I/O has been in HDF5 "forever".  The "why wasn't this collective"? routine was introduced in hdf5-1.8.0
=> Work in progress: collective data

include/highfive/H5PropertyList.hpp, include/highfive/bits/H5FileDriver_misc.hpp
Since HDF5 1.10.0 (march 2016), HDF5 has the ability to request "collective metadata".  When requested, HDF5 (internally) will use collective operations to update the data structures stored in the HDF5 file.    If not requested, every single process will make these data structure updates, resulting in lots of small reads and writes -- particularly at scale. 
This does not fix #112 but users who are interested in collective I/O optimizations and are OK with the restrictions collective I/O imposes (every process has to create datasets, every process has to call H5Dwrite etc) are likely to be interested in this optimization as well.
A "darshan" log of a four process `parallel_hdf5_write_dataset` example from HighFive tells me there were 0 MPI-IO collective writes, 11 MPI-IO …
=> Turn on collective HDF5 metadata

include/highfive/H5FileDriver.hpp, src/examples/parallel_hdf5_write_dataset.cpp, tests/unit/tests_high_five_base.cpp, tests/unit/tests_high_five_parallel.cpp
The current FileDriver implementations just inherit from
FileAccessProps, and I think that with further additions to the file
access property lists, it is cleaner to just use FileAccessProps
directly.
=> Deprecate FileDriver(s)

include/highfive/H5PropertyList.hpp, include/highfive/bits/H5PropertyList_misc.hpp, include/highfive/bits/H5Slice_traits.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, src/examples/parallel_hdf5_write_dataset.cpp, tests/unit/tests_high_five_parallel.cpp
This PR adds the ability to pass a data transfer property list to `read` and `write` operations. This is needed to enable collective MPI-IO.
In essence this is #621
=> Enable collective MPI IO.

include/highfive/H5File.hpp, include/highfive/bits/H5File_misc.hpp
Setting the file creation properties is essential when creating HDF5 files with non-stardard creation-time setting, such as paged allocation (aka file space strategy) or the sizes of internal data structures.
=> Enable passing file creation properties.

include/highfive/H5PropertyList.hpp, include/highfive/bits/H5PropertyList_misc.hpp, tests/unit/tests_high_five_base.cpp
The precise timing of when space is allocated for the raw data of a dataset can be configured via the dataset creation property list. This commit wraps the required HDF5 function.
=> Add wrapper for allocation time.

include/highfive/H5File.hpp, include/highfive/H5PropertyList.hpp, include/highfive/bits/H5File_misc.hpp, include/highfive/bits/H5PropertyList_misc.hpp, src/examples/create_page_allocated_files.cpp, tests/unit/tests_high_five_base.cpp
Implements support for the different file space strategies:
https://portal.hdfgroup.org/display/HDF5/H5P_SET_FILE_SPACE_STRATEGY
https://portal.hdfgroup.org/display/HDF5/H5P_SET_FILE_SPACE_PAGE_SIZE
including paged allocation with configurable page size. Since both are "file creation properties". This MR also includes a new ctor for `File` which enables creating files specifying both creation and access properties.
=> Implement file space strategies.

.github/workflows/clang_format.yml, include/highfive/H5Attribute.hpp, include/highfive/H5DataSet.hpp, include/highfive/H5DataType.hpp, include/highfive/H5File.hpp, include/highfive/H5Group.hpp, include/highfive/H5PropertyList.hpp, include/highfive/bits/H5File_misc.hpp
Usage
```c++
#include <highfive/H5File.hpp>
using namespace HighFive;
int main() {
File file{"a.h5"};
auto fapl = file.getAccessPropertyList();
return 0;
}
```
=> Add a function to get property list from object

AUTHORS.txt, CHANGELOG.md, CMakeLists.txt
- Enable collective MPI IO using the Data Transfer Property (#623). Thanks to Rob Latham.
- Add a support for half-precision (16-bit) floating-point based on the Half library (http://half.sourceforge.net) (#587). Thanks to Sergio Botelh.
- Enable choosing the allocation time of datasets (#627).
- Add possibility to get and set file space strategy. For page allocated files wrap the API to set/retrieve the page size (#618).
- Add API for getting Access and Create property lists of HighFive objects (#629).
- Let users configure metadata reads and writes at file level (#624). Thanks to Rob Latham.
- MPIOFileDriver is now deprecated. Use FileAccessProps (#622).
- Support of block argument in API (#584).
- Serialization of types is now automagic and so recursive (#586).
- Add an argument to …
=> Version 2.5.0

include/highfive/H5DataType.hpp, include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5ReadWrite_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, tests/unit/tests_high_five_base.cpp
HDF5 treats floats and doubles as Float, one datatype class. so reading a double dataset into a float vector won't even cause a warning message. This PR extends DataTypeClass a little bit to allow comparing DataTypeClasses with bit operators and then treats the case specially where datatypes are floating types and also checks the type size, printing a warning if there is a mismatch.
Here's a minimal patch to one of the examples that tests this:
```
--- a/src/examples/create_dataset_double.cpp
+++ b/src/examples/create_dataset_double.cpp
@@ -6,6 +6,7 @@
*          http://www.boost.org/LICENSE_1_0.txt)
*
*/
+#include <array>
#include <iostream>
#include <string>
#include <vector>
@@ -37,6 +38,15 @@ int main(void) {
// write it
dataset.write(data);
+ …
```
=> Check also datatype sizes for floats to avoid losing bits

CMake/HighFiveTargetDeps.cmake
This PR allows finding HDF5 when only `*-config.cmake` files are present, i.e. when the find module can't find HDF5, but in config mode the dependency could be found.
=> Allow finding HDF5 in config mode.

README.md, src/examples/readme_snippet.cpp
Changes the README to show the simple usecase and mention the advanced usecase, instead of showing the verbose variety and hinting at the available oneliner. A version of the code snippet is maintained in `examples/readme_snippet.cpp` (to check for compilation errors, and future breakage, etc.).
=> Simplify and modernize the README example.

include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp
Variable length strings are not of type VariableLength, so need to add a check for them.
Fix #658
=> Fix leak when reading variable length strings

.github/workflows/coverage.yml
There was a bug when trying to publish coverage for the merge inside master branch.
It seems that last version fix it.
Let see.
=> Use the new action for coverage

include/highfive/bits/H5Exception_misc.hpp
Please include a summary of the change and which issue is fixed or which feature is added.
Windows Visual Studio did not like the native call to `free(..)`. Using the Hdf5 function resolves the issue.
https://portal.hdfgroup.org/display/HDF5/H5_FREE_MEMORY
=> Use 'H5free_memory(void*)' instead of native 'free(void*)' in error handler.

.github/workflows/ci.yml, tests/unit/CMakeLists.txt, tests/unit/tests_high_five.hpp, tests/unit/tests_high_five_base.cpp, tests/unit/tests_high_five_easy.cpp, tests/unit/tests_high_five_multi_dims.cpp, tests/unit/tests_high_five_parallel.cpp
From 2 to v3, catch2 breaks a lot of things: fix it.
Will fix #668
=> Bump Catch2 to v3.2.1

.github/workflows/ci.yml
HDF5 1.13.x was a alpha version, let's move to the final version
=> Bump hdf5 from 1.13.x to 1.14.0

tests/unit/CMakeLists.txt, tests/unit/test_all_types.cpp
I will endly try to get a full tests of all types we support.
This PR is a WIP to fix #496
=> Add a test that test all types in a scalar way

include/highfive/H5File.hpp, src/examples/CMakeLists.txt, src/examples/hl_hdf5_inmemory_files.cpp
As discussed internally, one way of adding functionality related to inmemory file would be to subclass `HighFive::File`. In the PR this option is sketched out as an example.
This could be an alternative to implementing #648
=> Example of reading an in memory HDF5 file.

include/highfive/H5Group.hpp, include/highfive/H5PropertyList.hpp, include/highfive/bits/H5File_misc.hpp, include/highfive/bits/H5PropertyList_misc.hpp, src/examples/parallel_hdf5_collective_io.cpp, tests/unit/tests_high_five_parallel.cpp
=> Add access to values of properties

CMake/HighFiveTargetDeps.cmake
Forcing `Boost_NO_BOOST_CMAKE=On` was reported to cause build failure in:
https://github.com/BlueBrain/HighFive/issues/685
This commit keeps the current default, but respects the users choice.
=> Allow users to set `Boost_NO_BOOST_CMAKE`.

include/highfive/H5Attribute.hpp, include/highfive/H5Group.hpp, include/highfive/H5Object.hpp, include/highfive/H5Selection.hpp, include/highfive/bits/H5Annotate_traits_misc.hpp, include/highfive/bits/H5Node_traits_misc.hpp, include/highfive/bits/H5Object_misc.hpp, include/highfive/bits/H5Selection_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp
There seems to be a compiler bug in numerous version of GCC which
prevent code such as:
```c++
class Foo {
template<class Derived>
friend class SomeCRTP<Derived>;
};
```
This commit removed all such constructs from HighFive, by allowing a
function `detail::make_*` to create `Object`, `Selection` and `Group`
from an `hid_t`.
=> Avoid templated friend classes.

.github/workflows/ci.yml, CMakeLists.txt, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5DataType_misc.hpp, tests/unit/test_all_types.cpp
Add  support for std::byte as Dataset type when using c++17 and above 
Fixes #480 
```bash
cmake -DCMAKE_CXX_STANDARD=17 ..
make -j8
make test
```
- OS: [e.g. Ubuntu 20.04]
- Compiler: [e.g. clang 12.0.0]
- Dependency versions: [e.g. hdf5 1.12]
=> Fix : Add support for std::byte as Dataset type for c++17 and above

include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, tests/unit/tests_high_five_base.cpp
The integration tests show that we have issues when dealing with empty datasets, both when reading and writing them. This commit adds testing to cover reading and writing empty datasets using `std::vector`, `Eigen::*` and `boost::multi_array` for datasets and attributes. Furthermore, it fixes the discovered bugs.
=> Fix and test empty corner cases.

.github/workflows/coverage.yml
* `CODECOV_TOKEN` defined in secrets on GH
=> Coverage CI: use codecov token

README.md
This PR proposes to remove the codecov CI because it's been highly unreliable recently. I'd like to avoid getting used to failing CI. Therefore, I think it's best if we simply remove it for the time being.
Next this also removes a badge for static analysis which ran last in 2017.
=> Remove outdated badge.

include/highfive/H5File.hpp
Reverts removal of `#include<H5FileDriver.hpp>` from `#include <H5File.hpp>`.
=> Add missing include of `H5FileDriver.hpp`

include/highfive/bits/H5Object_misc.hpp
This PR fixes an import statement that causes compilations to fail when trying to use HighFive as a header-only library with custom install locations. Symptoms are: (i) `fatal error: 'highfive/H5Utiity.hpp' not found` if the conda environment does not contain a system `highfive` or (ii) a long error stack starting with `error: redefinition of 'SilencedHDF5' [...]` if trying to compile with a custom location while having a `highfive` package installed. Using the relative import (which is used everywhere else) fixes the issue. 
```bash
cmake ..
make -j8
make test
```
- OS: macOS (inside `conda` environment with/without `highfive` package installed)
- Compiler: AppleClang 14.0.3 
- Dependency versions: hdf5 1.12
=> Fix compilation failures for custom installation locations

include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5DataType_misc.hpp
=> Avoid name collision with macros `TRUE` and `FALSE`.

.github/workflows/ci.yml, CMake/HighFiveTargetDeps.cmake, CMakeLists.txt, include/highfive/H5Attribute.hpp, include/highfive/H5File.hpp, include/highfive/H5Group.hpp, include/highfive/H5Object.hpp, include/highfive/H5Selection.hpp, include/highfive/H5Utility.hpp, include/highfive/bits/H5Friends.hpp, include/highfive/bits/H5Utils.hpp
The purpose of this MR is to get older versions of MSVC to compile HighFive. The hope is it'll reproduce the issue in #724. This fixes required are also included in this PR.
=> Avoid MSVC compiler bug.

CHANGELOG.md, CMakeLists.txt
This time we ran the deployment with the HighFive Spack recipe pointing `highfive@2.7.1` at commit `11e45f00303305dd409a5c8865a0e9dacce3cd5d`.
=> Prepare version 2.7.1.

include/highfive/bits/H5Path_traits_misc.hpp
GCC 12 warns that `static_cast<Derived*>(*this)->getId()` dereferences a null pointer. We can use references instead.
=> Prefer reference over pointer.

include/highfive/bits/H5DataType_misc.hpp
This add wrappers that perform the required error checking for commonly used `H5T*` functions. The wrappers are intentionally kept internal.
=> Add wrapper for commonly used 'H5T*' functions.

include/highfive/bits/H5Slice_traits.hpp, include/highfive/bits/H5Slice_traits_misc.hpp
This commit allows users to specify the memory dataspace. Previously, we forced the memspace to be 1D, because in general a hyperslab selection isn't a multi-dimensional block anymore.
We now allow users to specify the memory dataspace, which must be simple; but can be multi-dimensional.
=> Allow user-specified `mem_space` for hyperslabs.

CMake/HighFiveConfig.cmake.in, CMakeLists.txt, tests/test_dependent_library/CMakeLists.txt, tests/test_project_integration.sh
The `packageConfig.cmake` was not respecting QUIET request. Further, it seems that we were not calling `check_required_components` which is pretty standard to validate component request.
Fixes #593
Tested locally, launching `test_project_integration.sh`
```bash
cd HighFive/tests
bash test_project_integration.sh
```
=> Improve Cmake detection quietness, and adhere to standard procedure

README.md
We don't use Travis anymore, so we can remove the badge.
=> Remove Travis CI badge.

codecov.yml
The previous attempt was incomplete and didn't cover patches. This means that we can't commit examples anymore, since those count as no tested.
See https://docs.codecov.com/docs/common-recipe-list
=> Use codecov in "informational" mode.

src/examples/boost_multi_array_2D.cpp, src/examples/boost_multiarray_complex.cpp, src/examples/compound_types.cpp, src/examples/create_attribute_string_integer.cpp, src/examples/create_dataset_double.cpp, src/examples/create_dataset_half_float.cpp, src/examples/create_datatype.cpp, src/examples/create_extensible_dataset.cpp, src/examples/create_page_allocated_files.cpp, src/examples/easy_attribute.cpp, src/examples/hl_hdf5_inmemory_files.cpp, src/examples/parallel_hdf5_collective_io.cpp, src/examples/parallel_hdf5_independent_io.cpp, src/examples/read_write_dataset_string.cpp, src/examples/read_write_fixedlen_string.cpp, src/examples/read_write_raw_ptr.cpp, src/examples/read_write_single_scalar.cpp, src/examples/read_write_vector_dataset.cpp, src/examples/read_write_vector_dataset_references.cpp, src/examples/readme_snippet.cpp, src/examples/select_by_id_dataset_cpp11.cpp, src/examples/select_partial_dataset_cpp11.cpp
This is a mostly mechanical change to remove the catch-all blocks from the examples. The idea is that if we run them during CI, we'd like to know if they fail.
=> Remove the 'try-catch' constructs from examples.

.github/workflows/ci.yml
We use `include:` to run all combinations of Windows, even if they cant' exactly be described by a matrix.
=> Make ci.yml DRYer.

.github/workflows/ci.yml
This aim is to prevent build failures, e.g. missing `inline`, when using a parallel version of HDF5. In HighFive there's some code that's only compiled with the parallel version of HDF5. See #638.
=> Also run project integration CI for pHDF5.

include/highfive/H5DataType.hpp
=> Fix vector constructor ambiguity in H5DataType.hpp

.github/workflows/ci.yml
Apparently, `provision-with-micromamba` is deprecated and we need to use `setup-micromamba` from now on. There's a migration guide here: https://github.com/mamba-org/provision-with-micromamba#migration-to-setup-micromamba
=> Modernize mamba Github Action.

include/highfive/bits/H5Dataspace_misc.hpp, tests/unit/tests_high_five_base.cpp
For null dataspaces `getElementCount()` would return 1 instead of 0.
=> Fix and test bug in `getElementCount()`.

include/highfive/bits/H5Inspector_misc.hpp
Improving the string support requires that (de-)serialization can happen from an iterator, as opposed to the current `hdf5_type*`.
This commit prepares the containers which largely just move the pointer forward by the correct number of elements and hand it over to the next serialization routine of its elements, so that they can accept something pointer like, i.e. an iterator.
=> Prepare inspector for non-`hdf5_type*` iterators.

include/highfive/H5DataType.hpp, tests/unit/tests_high_five_base.cpp
Tests have been run with and without fix.
=> Free return of H5Tget_member_name

include/highfive/H5DataType.hpp, include/highfive/bits/H5Node_traits.hpp, include/highfive/bits/H5Node_traits_misc.hpp, tests/unit/tests_high_five_base.cpp
HighFive provides the ability to commit datatypes to files with CompoundType::commit for example but does not provide the ability to open the previously commited datatypes.
This PR enhance the Node Traits to get the datatype stored in that node.
```bash
cmake ..
make -j8
make test
```
-OS: Ubuntu 22.04.2 LTS (WSL)
-Compiler: gcc 11.3.0
-Dependency versions: hdf5 1.10.7
=> Read datatype

include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp
This commit introduces the internal notion of buffers. We already need to copy non-contiguous data into a contiguous buffer. This commit simply makes this idea more explicit.
The advantage is that each class can focus on its purpose and thereby simplify its code.
=> Introduce '{Shallow,Deep}CopyBuffer'.

include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp
The upcoming `StringBuffer` will need to know the file datatype, because in HDF5 the expect datalayout, and therefore the way the buffer is populated, is different for fixed and variable length strings.
=> Allow Buffers to depend on the file datatype.

.github/workflows/ci.yml
This PR adds tests which check that HighFive compiles as a C++20 project, e.g. #811 will add concepts which were introduced in C++20.
=> Compile HighFive as C++20 project.

CMake/HighFiveTargetDeps.cmake, CMakeLists.txt, include/highfive/H5PropertyList.hpp, include/highfive/bits/H5PropertyList_misc.hpp
The property struct/class requires a public member function signature `apply(hid_t) const`. Describe the constrain in the C++20 concepts syntax. The primarily goal is to make compiler errors more readable for average users. Average users are those who do not understand SFINAE.
Resolves feature #810 .
It is a compile-time type checking. If the production code or test code compiles, the code is valid.
- OS: Ubuntu 20.04
- Compiler: clang 12.0 with C++20 and/or C++11
- Dependency versions: Irrelevant.
=> Constrain the Property object at compile-time

include/highfive/bits/H5Inspector_misc.hpp
Prior to this commit GCC 13 would emit numerous warnings related to `-Warray-bounds`. There are numerous similar have been reported, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56456
This PR replaces the `std::copy` with the equivalent loop.
=> Avoid spurious GCC 13 array-bounds warnings.

include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp
There's a notion of pointer to the first byte of the buffer. This is what one passes to HDF5, e.g. in `H5Dread`. There's also the concept of a iterator which is used for serialization.
Currently, both ideas are represented by an `hdf5_type*`. However, the StringBuffer will need to return proxy objects. This commits splits the notion. Conveniently, we can rename `get_pointer` to the more in-style `getPointer` and hence the compiler checks that we've considered all occurrences of `get_pointer`.
=> Distinguish between buffer pointer and iterator.

.github/workflows/ci.yml, tests/unit/test_all_types.cpp, tests/unit/tests_high_five.hpp, tests/unit/tests_high_five_base.cpp, tests/unit/tests_high_five_easy.cpp
Since HDF5 locks a file, running tests in parallel will fail if the file names aren't unique.
=> Use unique filenames in tests.

doc/developer_guide.md
Adds a missing equal sign to pin the version of clang.
Create virtual environment according to current guide...
```
$ pip install clang-format=12.0.1
ERROR: Invalid requirement: 'clang-format=12.0.1'
Hint: = is not a valid operator. Did you mean == ?
```
...versus running it according to the fixed guide:
```
$ pip install clang-format==12.0.1
Collecting clang-format==12.0.1
```
=> fix typo in developer_guide.md

include/highfive/bits/H5DataType_misc.hpp, tests/unit/tests_high_five_easy.cpp
Among other functionality, H5Easy allows reading and writing of vectors of standard types.
However, an assertion prevents use of vector of complex integral numbers for `H5Easy::load` and `H5Easy::dump`.
Example:
```
std::vector<std::complex<int16_t>> ds;
ds = H5Easy::load<std::vector<std::complex<int16_t>>>(const File& file, const std::string& path)
H5Easy::dump(const File& file, const std::string& path, ds)
```
This pull request modifies the the assertion to allow integral types and enable H5Easy support for complex integral type.
I have tested the modified code in a non-public application for `complex<int16_t>`. ~~I have not tested other cases at this time, but would be happy to extend HighFive test's where appropriate. I am not familiar with the …
=> H5Easy support for complex integral type

tests/unit/tests_high_five_base.cpp
Add explicit comments based on conversation in #831 for future reference. No functional change.
=> add comments to code for future reference, no functional change

.github/workflows/version_file.yml, CMake/HighFiveTargetExport.cmake, CMakeLists.txt, include/highfive/H5Version.hpp
Generated files require users to "build" and "install" HighFive, for the sole purpose of having files generated via `configure_file` available. The only file that generated in HighFive is the version file.
This PR proposes to automatically generate the file but also commit it to the repo. The advantage of doing so, is that users can clone the repo, set the appropriate value for `-I` and they're done (if they don't need any addons).
In order to check that the version number in `CMakeLists.txt` and `H5Version.hpp` are consistent we configure HighFive during CI and check that the file hasn't changed.
=> Include `H5Version.hpp` in the sources.

include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5DataType_misc.hpp, include/highfive/bits/H5Inspector_misc.hpp, include/highfive/bits/H5ReadWrite_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, src/examples/read_write_std_strings.cpp, tests/unit/tests_high_five_base.cpp
This PR outlines how one could read and write `std::string` and containers of `std::string` into/from fixed or variable length HDF5 strings.
=> Flexible `std::string`s.

include/highfive/bits/H5Node_traits.hpp, include/highfive/bits/H5Node_traits_misc.hpp
Avoids #841 since the extra complexity isn't needed.
=> Simplify internal method `_open`.

tests/unit/tests_high_five_base.cpp
This isn't desired behaviour. However, it's non-obvious and users might rely on it. Hence, it's being tested.
=> Enshrine observable, but quirky behaviour.

include/highfive/bits/H5DataType_misc.hpp, tests/unit/tests_high_five_base.cpp
Create the specialization from `create_datatype<bool>` and adds the tests to check that raw arrays of bool are bitwise compatible with the enum that's serialized.
=> Fix `create_datatype<bool>()`.

.github/workflows/ci.yml, include/highfive/H5DataType.hpp
HDF5 errors that aren't promoted to an exception by HighFive will simply print an error message. This means that tests can pass even if there are HDF5 errors. This will run the tests with `ctest --verbose` and check that the output doesn't contain `"HDF5-DIAG"`.
=> Check `ctest` output for HDF5-DIAG.

tests/unit/tests_high_five_base.cpp
Instead of comparing values, use `std::memcmp` to compare bytes.
=> Improve `details::Boolean` compatibility checks.

include/highfive/bits/H5DataType_misc.hpp, include/highfive/bits/H5Object_misc.hpp, include/highfive/bits/H5Path_traits_misc.hpp, include/highfive/bits/H5Reference_misc.hpp, include/highfive/bits/h5i_wrapper.hpp
This wrapper enables us to see more easily notice that an error code is being ignored, makes it very clear how we wrap HDF5 function and encourages us to not ignore unchecked error codes if we see one. It'll make it easier to have uniform error handling. Additionally, it prepares the way towards more interesting features, such as thread-safety or logging each call to HDF5 (for creating pure HDF5 reproducers).
The rules are:
1. Each HDF5 "function" `H5?*` is wrapped by `detail::h5?_*`. We can't reuse the name in a namespace because some of them are macros.
2. Unless the wrapped function is in the namespace `detail::nothrow` it'll throw whenever the returned value indicates an error.
3. The arguments to `H5?*` and `detail::h5?_*` are identical.
4. Outside of the files `h5?_wrapper.hpp` we …
=> Complete the low-level wrapper of all used HDF5 functions.

include/highfive/bits/H5DataType_misc.hpp, include/highfive/bits/H5Inspector_decl.hpp, include/highfive/bits/H5Inspector_misc.hpp, include/highfive/boost.hpp, include/highfive/eigen.hpp, include/highfive/half_float.hpp, src/examples/create_dataset_half_float.cpp, tests/unit/tests_high_five.hpp
The file containing the specializations of traits for specific optional dependencies have been moved to their own files. This allows us to move to macro free dependency handling, simply by removing certain guarded includes.
=> Restructure dependency handling.

include/highfive/H5DataSpace.hpp, include/highfive/bits/H5Dataspace_misc.hpp, include/highfive/bits/h5s_wrapper.hpp, tests/unit/tests_high_five_base.cpp
The issue is that:
```
DataSpace{DataSpace::dataspace_scalar};
DataSpace{DataSpace::dataspace_null};
```
are a simple dataspace with 0 elements and a simple dataspace with one element, respectively. This provides a safer alternative.
=> Add named ctors for scalar and null dataspaces.

doc/developer_guide.md, tests/unit/create_traits.hpp, tests/unit/data_generator.hpp, tests/unit/supported_types.hpp, tests/unit/test_all_types.cpp, tests/unit/tests_high_five_multi_dims.cpp
Adds/reimplements abstractions for the following:
* Create multi-dimensional array filled with suitable values.
* Traits for accessing values.
* Traits for hiding the difference of DataSet and Attribute.
* Useful utilities such as `ravel`, `unravel` and `flat_size`.
=> Improve testing infrastructure.

include/highfive/bits/H5Inspector_misc.hpp
Handle empty containers directly in the inspector.
=> 'inspector` guard for empty containers.

include/highfive/bits/H5Slice_traits_misc.hpp, tests/unit/tests_high_five_parallel.cpp
MPI collective IO, requires that certain HDF5 functions are called collectively. Here some short-circuiting logic for empty datasets interferes when some, but not all, selections from different MPI ranks are empty.
=> Avoid non-collective behaviour.

include/highfive/bits/H5Node_traits.hpp, include/highfive/bits/H5Node_traits_misc.hpp
This was likely needed to hide the bug that the specialization for `create_datatype<bool>` was missing. See, commit 9415a7c82.
=> Remove unused specialization for createDataSet.

include/highfive/bits/H5Inspector_misc.hpp
Adds `prepare` and `data` (non-cost) methods to `inspector<T[N]>`. This is needed to serialize a `int a[][] = {{1, 2, 3}, {4, 5, 6}};` without the `read(T*, ...)` overload.
=> Fix `inspector<T[N]>`.

tests/unit/CMakeLists.txt, tests/unit/test_legacy.cpp, tests/unit/tests_high_five_base.cpp
This new groups of tests isolates tests the are counter-intuitive from the rest. This makes it easier to review them, and makes it clear that they're considered odd by someone else; and therefore might even be testing buggy behaviour.
=> Move strange test to `test_legacy.cpp`.

include/highfive/bits/H5DataType_misc.hpp, include/highfive/bits/H5Inspector_misc.hpp, include/highfive/boost.hpp, include/highfive/eigen.hpp, include/highfive/half_float.hpp, src/examples/boost_multi_array_2D.cpp, src/examples/boost_multiarray_complex.cpp, src/examples/boost_ublas_double.cpp, src/examples/create_dataset_half_float.cpp, tests/unit/CMakeLists.txt, tests/unit/data_generator.hpp, tests/unit/tests_high_five.hpp, tests/unit/tests_high_five_base.cpp, tests/unit/tests_high_five_multi_dims.cpp
Sketch of how we could reorganize our headers to allow each code to pick their dependencies simply by choosing which headers they include. This is similar to how pybind11 handles their convertors between Python types and say STL containers.
=> Macro free dependency handling.

include/highfive/H5DataSpace.hpp, tests/unit/tests_high_five_base.cpp
See #899 for what the issue is and a safe alternative. Unfortunately, changing an enum to an enum class is a breaking change and can't be done until `3.0.0`.
=> Use enum class for DataSpace::DataspaceType. 

.github/workflows/ci.yml, .github/workflows/clang_format.yml, .github/workflows/coverage.yml, .github/workflows/gh-pages.yml, .github/workflows/version_file.yml
The tests should run for every PR and when merged into the main or `v2.x` branch. Docs should be published only when merging into `v2.x` (for now).
We've removed `release/**` since we don't have those. It also removes `ci_test` because I haven't seen anyone test the CI that way, `git commit --allow-empty` can be used instead.
=> Fix when CI is run.

include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5Inspector_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, include/highfive/boost.hpp, include/highfive/eigen.hpp
By passing the dimensions to `serialize` allows serializing nested pointers. This was previously not possible because, we didn't know how many elements the pointer pointed to.
The logic for obtaining the dimensions of the array is:
* When creating/opening the array the memspace is set to be the same as the filespace.
* Performing a selection either leads to a simple (packed) multi-dimensional memspace; or to a one-dimensional memspace.
Therefore, if we perform a write without selection, we know the dimensions the input array must have. If we perform a selection we again know the dimensions the input buffer needs to have.
=> Pass dimensions to 'serialize'.

include/highfive/bits/H5Converter_misc.hpp, include/highfive/bits/H5Inspector_misc.hpp, include/highfive/boost.hpp, include/highfive/eigen.hpp
The method `getSizeVal(T& value)` is problematic because some containers don't know their dimensions, yet they need to forward the input pointer when serializing/deserializing. After changing `serialize` to accept the `dims` the number of elements can be obtained from there. It's also tricky in the context of arrays of chars, these could be a counted as one string or as multiple characters. Inside the inspector we don't know which interpretation is correct.
The method `getSize(dims)` seems to only have a single plausible implementation. Hence, it's being removed mostly for cosmetic reasons.
=> Remove `inspector<T>::getSize{,Val}`.

.github/run_examples.sh, .github/workflows/ci.yml
Counter example:
https://github.com/BlueBrain/HighFive/actions/runs/7976398553/job/21776889696?pr=947
=> Windows CI must be red when tests fail.

cmake/HighFiveWarnings.cmake, src/examples/CMakeLists.txt, tests/unit/CMakeLists.txt
Frequently, GCC prints error messages, but, ironically, they're too short, it'll include the inner most context, somewhere deep inside the STL or some other external libary, then skip all the HighFive context and continue printing the outer most layers which typically happen to be in Catch2.
=> Improve information content of GCC error messages.

include/highfive/h5easy_bits/H5Easy_xtensor.hpp, tests/unit/tests_high_five_easy.cpp
Easy serializes XTensor objects by obtaining a pointer to the first element, and then using `write_raw`. Same for reading using `read_raw`.
Therefore, it only supports (a subset of) row-major arrays. This commit as a runtime check.
=> Assert that XTensor objects are row-major.

include/highfive/bits/H5Inspector_misc.hpp, include/highfive/boost.hpp, include/highfive/eigen.hpp
We need this because `std::span` is considered `std::is_trivially_copyable`.
=> Add `inspector::is_trivially_nestable`.

tests/unit/tests_high_five_base.cpp
There's three copies of unifying API for DataSet and Attribute. This
removes two copies.
=> Remove duplicates of unifying test API.

include/highfive/H5Attribute.hpp, include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5Inspector_decl.hpp, include/highfive/bits/H5Slice_traits.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, include/highfive/bits/compute_total_size.hpp, include/highfive/bits/squeeze.hpp, src/examples/CMakeLists.txt, src/examples/broadcasting_arrays.cpp, tests/unit/tests_high_five_base.cpp
These methods allow reshaping the memory space. This can be used as
an alternative to broadcasting.
Example:
Let `dset` be a dataset with shape `[3, 1, 1]`. Then,
dset.reshapeMemSpace({3}).read<std::vector<double>>();
dset.squeezeMemSpace({1, 2}).read<std::vector<double>>();
can be used to read into a one-dimensional dataset.
=> Implement `squeeze` and `reshape`.

include/highfive/bits/H5Attribute_misc.hpp, include/highfive/bits/H5DataType_misc.hpp, include/highfive/bits/H5Dataspace_misc.hpp, include/highfive/bits/H5Inspector_misc.hpp, include/highfive/bits/H5ReadWrite_misc.hpp, include/highfive/bits/H5Slice_traits_misc.hpp, include/highfive/boost.hpp, include/highfive/eigen.hpp, include/highfive/span.hpp, tests/unit/data_generator.hpp
The commit removes the requirement for a constexpr rank. Instead
containers need a minimum and maximum constexpr rank.
The difficulties are:
* Empty arrays can't figure out their runtime rank. This is an issue
when deducing the dimension when writing to disk. The "solution" is
to deduce with lowest rank possible.
=> No constexpr rank via constexpr min-max rank.

.github/workflows/ci.yml
I seem that Windows 2022 now uses Visual Studio 2022 17.9 and doesn't include toolset `v141` anymore.
=> Update Window CI.

.github/workflows/ci.yml, doc/migration_guide.md, include/highfive/H5PropertyList.hpp, include/highfive/bits/H5PropertyList_misc.hpp
These are abstract concepts in the documentation of HDF5. In their current implementation they can't be used to express "one of ..." as they should.
=> Remove `Object{Create,Access}Props`.

include/highfive/H5Object.hpp, include/highfive/bits/H5Node_traits.hpp, include/highfive/bits/H5Node_traits_misc.hpp, include/highfive/bits/H5Object_misc.hpp, include/highfive/bits/h5o_wrapper.hpp
Since deleting HighFive objects through their common base class `Object` is not supported, we should make the dtor protected.
See Core Guidelines C35, e.g.
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-dtor-virtual
=> Make `~Object` protected.

include/highfive/xtensor.hpp, tests/unit/CMakeLists.txt, tests/unit/data_generator.hpp, tests/unit/supported_types.hpp, tests/unit/test_xtensor.cpp, tests/unit/tests_high_five.hpp
Adds support for `xt::xtensor`, both row and column major. We're missing `xt::xarray` and views. Views fail because they claim to have runtime variable rank.
=> Implement XTensor support in core.

.github/workflows/ci.yml
Since a recent update it seems that Windows 2022 now uses Visual Studio 2022 17.9 and doesn't include toolset v141 anymore.
=> backport: Update Windows CI.

include/highfive/H5DataSpace.hpp, include/highfive/bits/H5Dataspace_misc.hpp
Certain HDF5 API creates data spaces, in order to use this API, we need to be able to create `HighFive::DataSpace` from an HID.
=> Add private DataSpace (named) ctor `fromId`.

include/highfive/H5DataSpace.hpp, include/highfive/bits/H5Dataspace_misc.hpp
Certain HDF5 API creates data spaces, in order to use this API, we need to be able to create `HighFive::DataSpace` from an HID.
=> backport: Add private DataSpace (named) ctor `fromId`.

include/highfive/bits/H5Slice_traits.hpp, include/highfive/bits/h5s_wrapper.hpp, tests/unit/test_high_five_selection.cpp
A common pattern for creating semi-unstructured selection is to use many
(small) RegularHyperSlab and chain them:
```
HyperSlab hyperslab;
for(auto slab : regular_hyper_slabs) {
hyperslab |= slab;
}
```
This eventually triggers calling:
```
for(auto slab : regular_hyper_slabs) {
auto [offset, stride, counts, blocks] = slab;
H5Sselect_hyperslab(space_id, offset, stride, counts, block);
}
```
Measurements show that this has runtime that's quadratic in the number
of regular hyper slabs. This starts becoming prohibitive at 10k - 40k
slabs.
We noticed that `H5Scombine_select` does not suffer from the same
performance issue. This allows us to optimize (long) chain of `Op::Or`
using divide and conquer.
The current implementation only optimizes streaks of `Op::Or`.
=> Optimize chained hyperslab selection.

include/highfive/H5DataType.hpp, include/highfive/bits/H5Converter_misc.hpp, tests/unit/test_string.cpp
See #1054. Essentially, it seems that fixed-length strings that have a padding mode that suggests they're null-terminated are in fact not required to be null-terminated. HDF5 will create such string, `h5dump` will display the file and `h5py` will read the string.
HighFive will continue to not allow writing null-terminated strings that aren't. This PR proposes that it should allow reading such strings into `std::string`.
=> Allow reading not-quite null-terminated strings.

include/highfive/H5DataType.hpp, include/highfive/bits/H5Converter_misc.hpp, tests/unit/tests_high_five_base.cpp
For fixed-length strings that have a padding mode that suggests they're null-terminated are in fact not required to be null-terminated, we (silently) fail to read the last character. Since, HDF5 will create such string, h5dump will display the file and h5py will read the string; we opted to allow it and also read the string into and `std::string` (which is variable length and already not guaranteed to have the same length as the fixed length string).
HighFive will continue to not allow writing null-terminated strings that aren't via `write`.
Backports: https://github.com/BlueBrain/HighFive/pull/1056
=> backport: Allow reading not-quite null-terminated strings.
